name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add this permissions block
permissions:
  contents: read
  statuses: write  # This is required for creating commit statuses

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./my-cool-site

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './my-cool-site/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: |
          npm run lint
          npm run format -- --check

      # Status check reporting
      - name: Report Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const { conclusion } = context.payload.workflow_run || { conclusion: context.job.status };
            const message = conclusion === 'success'
              ? '✅ Linting passed'
              : '❌ Linting failed';

            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: conclusion === 'success' ? 'success' : 'failure',
              description: message,
              context: 'Lint Check'
            });
